name: Deploy to Heroku

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Grant execute permission for gradlew
      run: chmod +x ./Backend/gradlew
    
    - name: Run tests
      run: |
        cd Backend
        ./gradlew test
        cd ..

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Copy Frontend to Backend
      run: |
        mkdir -p Backend/src/main/resources/static
        cp -r Frontend/*.html Backend/src/main/resources/static/
        cp -r Frontend/css Backend/src/main/resources/static/
        cp -r Frontend/js Backend/src/main/resources/static/
        cp -r Frontend/assets Backend/src/main/resources/static/
    
    - name: Build application
      run: |
        cd Backend
        chmod +x gradlew
        ./gradlew clean build -x test
        cd ..
    
    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.14
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
        heroku_email: ${{secrets.HEROKU_EMAIL}}
        usedocker: false
